default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: petit_blog_development
test:
  <<: *default
  database: petit_blog_test
production:
  <<: *default
  database: petit_blog_production
  username: petit_blog
  password: <%= ENV['PETIT_BLOG_DATABASE_PASSWORD'] %>
